#!/usr/bin/env python3
"""Generate the installable Bedder skill from the agent documentation."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parent.parent
SOURCE_PATH = REPO_ROOT / "docs" / "agent-skill.md"
OUTPUT_PATH = REPO_ROOT / "bedder-skill" / "SKILL.md"

FRONTMATTER = """---
name: bedder-skill
description: "Run Bedder for genomic interval intersections, subtraction, nearest-neighbor searches, mapping, and custom output columns. Use when an agent needs to construct or debug bedder CLI commands; process BED, VCF, or BCF intervals; choose overlap and reporting semantics; create Python callback scripts for --python, py: columns, filters, or map operations; inspect Bedder's Python callback object model; or validate Bedder results across versions."
---
"""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Build bedder-skill/SKILL.md from docs/agent-skill.md."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail instead of writing when SKILL.md is out of date",
    )
    return parser.parse_args()


def render() -> str:
    body = SOURCE_PATH.read_text(encoding="utf-8").strip()
    if not body.startswith("# "):
        raise ValueError(f"expected a level-one heading in {SOURCE_PATH}")
    notice = (
        "<!-- Generated by scripts/generate_skill.py from docs/agent-skill.md. "
        "Edit the documentation source, then regenerate. -->"
    )
    return f"{FRONTMATTER}\n{notice}\n\n{body}\n"


def main() -> int:
    args = parse_args()
    if not SOURCE_PATH.is_file():
        print(f"error: documentation source not found: {SOURCE_PATH}", file=sys.stderr)
        return 2

    try:
        expected = render()
    except (OSError, ValueError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 2

    current = OUTPUT_PATH.read_text(encoding="utf-8") if OUTPUT_PATH.exists() else None
    if args.check:
        if current != expected:
            print(f"out of date: {OUTPUT_PATH}", file=sys.stderr)
            return 1
        print(f"up to date: {OUTPUT_PATH}")
        return 0

    if current == expected:
        print(f"unchanged: {OUTPUT_PATH}")
        return 0

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(expected, encoding="utf-8")
    print(f"generated: {OUTPUT_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
